// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"github.com/serendipityConfusion/notification-platform/internal/api/grpc"
	"github.com/serendipityConfusion/notification-platform/internal/ioc"
	"github.com/serendipityConfusion/notification-platform/internal/repository"
	"github.com/serendipityConfusion/notification-platform/internal/repository/cache/redis"
	"github.com/serendipityConfusion/notification-platform/internal/repository/dao"
	"github.com/serendipityConfusion/notification-platform/internal/service"
)

// Injectors from wire.go:

func InitGrpcServer() *ioc.App {
	db := ioc.InitDB()
	notificationDAO := dao.NewNotificationDAO(db)
	client := ioc.InitRedis()
	quotaCache := redis.NewQuotaCache(client)
	notificationRepository := repository.NewNotificationRepository(notificationDAO, quotaCache)
	serviceService := service.NewNotificationService(notificationRepository)
	notificationServer := grpc.NewServer(serviceService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.InitGrpc(notificationServer, clientv3Client)
	app := &ioc.App{
		GrpcServer: server,
	}
	return app
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitIDGenerator, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitJeagerTracer)

	notificationSvcSet = wire.NewSet(service.NewNotificationService, repository.NewNotificationRepository, dao.NewNotificationDAO, redis.NewQuotaCache)
)
