// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"github.com/serendipityConfusion/notification-platform/internal/api/grpc"
	"github.com/serendipityConfusion/notification-platform/internal/ioc"
	"github.com/serendipityConfusion/notification-platform/internal/pkg/config"
	"github.com/serendipityConfusion/notification-platform/internal/pkg/registry"
	"github.com/serendipityConfusion/notification-platform/internal/repository"
	"github.com/serendipityConfusion/notification-platform/internal/repository/cache/redis"
	"github.com/serendipityConfusion/notification-platform/internal/repository/dao"
	"github.com/serendipityConfusion/notification-platform/internal/service"
)

// Injectors from wire.go:

func InitGrpcServer() *ioc.App {
	db := ioc.InitDB()
	notificationDAO := dao.NewNotificationDAO(db)
	client := ioc.InitRedis()
	quotaCache := redis.NewQuotaCache(client)
	notificationRepository := repository.NewNotificationRepository(notificationDAO, quotaCache)
	serviceService := service.NewNotificationService(notificationRepository)
	notificationServer := grpc.NewServer(serviceService)
	server := ioc.InitGrpc(notificationServer)
	clientv3Client := ioc.InitEtcdClient()
	etcdRegistry := ioc.InitRegistry(clientv3Client)
	viperConfigLoader := ioc.InitConfigLoader()
	serviceInfo := ioc.InitServiceInfo()
	app := &ioc.App{
		GrpcServer:   server,
		Registry:     etcdRegistry,
		ConfigLoader: viperConfigLoader,
		ServiceInfo:  serviceInfo,
	}
	return app
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitIDGenerator, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitJeagerTracer)

	// RegistrySet 服务注册相关依赖
	RegistrySet = wire.NewSet(ioc.InitRegistry, ioc.InitConfigLoader, ioc.InitServiceInfo, wire.Bind(new(registry.Registry), new(*registry.EtcdRegistry)), wire.Bind(new(config.ConfigLoader), new(*config.ViperConfigLoader)))

	notificationSvcSet = wire.NewSet(service.NewNotificationService, repository.NewNotificationRepository, dao.NewNotificationDAO, redis.NewQuotaCache)
)
